#!/usr/bin/env python
"""
Test Supabase PostgreSQL Connection
Helps diagnose database configuration issues
"""

import os
from dotenv import load_dotenv

load_dotenv()

print("=" * 70)
print("🗄️  Supabase Database Connection Test")
print("=" * 70)

db_url = os.getenv("DATABASE_URL", "").strip()

print(f"\n📍 DATABASE_URL from .env:")
print(f"   {db_url[:50]}..." if len(db_url) > 50 else f"   {db_url}")

# Check if placeholder
if "[YOUR-PASSWORD]" in db_url or db_url == "":
    print("\n❌ DATABASE_URL Not Configured!")
    print("\nYou need to update .env with your Supabase credentials:")
    print("\n1. Go to: https://supabase.com/dashboard")
    print("2. Select your project: nujhrwxhvprfugbdsrdr")
    print("3. Click: Settings → Database → Connection info")
    print("4. Under 'Connection string' (URI mode)")
    print("5. Copy the full URL (it contains your password)")
    print("\n6. Update .env:")
    print("   DATABASE_URL=postgresql://postgres.XXXXXX:PASSWORD@aws-1-ap-south-1.pooler.supabase.com:6543/postgres")
    print("\n7. Save .env and refresh the app")
    exit(1)

print("\n🔐 Testing PostgreSQL connection...")

try:
    import psycopg2
    conn = psycopg2.connect(db_url)
    cur = conn.cursor()
    
    print("✅ Connected to PostgreSQL!")
    
    # Test table creation
    cur.execute('''
        CREATE TABLE IF NOT EXISTS email_subscribers (
            id bigint generated by default as identity primary key,
            email text unique not null,
            subscribed boolean default true,
            frequency text default 'daily',
            created_at timestamp with time zone default now(),
            last_sent timestamp with time zone
        )
    ''')
    conn.commit()
    print("✅ Email subscribers table ready!")
    
    # Get row count
    cur.execute('SELECT COUNT(*) FROM email_subscribers')
    count = cur.fetchone()[0]
    print(f"✅ Current subscribers: {count}")
    
    cur.close()
    conn.close()
    
    print("\n" + "=" * 70)
    print("✅ ALL TESTS PASSED!")
    print("=" * 70)
    print("\nYour database connection is working perfectly.")
    print("You can now use the app to manage subscribers and send emails.")
    
except ModuleNotFoundError:
    print("❌ psycopg2 not installed!")
    print("\nFix: pip install psycopg2-binary")
    
except psycopg2.OperationalError as e:
    print(f"\n❌ Connection Failed!")
    print(f"Error: {e}")
    print("\nFix: Check your DATABASE_URL in .env")
    print("   - Make sure password is correct")
    print("   - Make sure it's the full connection string (not placeholder)")
    print("   - No quotes around the URL")
    
except Exception as e:
    print(f"\n❌ Error: {e}")

print("\n" + "=" * 70)
